spring:
    application:
        name: guess_system
    datasource:
        url: jdbc:mysql://localhost:3306/guess_db
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.app.guess.model
  configuration:
        map-underscore-to-camel-case: true

jwt:
    access-token-key: my-secret-key-my-secret-key-my-secret-key
    refresh-token-key: my-refresh-secret-key-my-refresh-secret-key-my-refresh-secret-key
    access-token-expiration: 90000 # 15 minutes
    refresh-token-expiration: 604800000 # 7 days
