spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.app.guess.model
  configuration:
    map-underscore-to-camel-case: true

jwt:
  access-token-key: ${JWT_ACCESS_TOKEN_KEY}
  refresh-token-key: ${JWT_REFRESH_TOKEN_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

vnpay:
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}
  payUrl: ${VNPAY_PAY_URL}
  returnUrl: ${VNPAY_RETURN_URL}
